name: SuperiorSkyblock-ASWM
version: 1.0.2
api-version: 1.16
authors: [Ome_R, aglerr]
main: me.aglerr.ssbslimeworldmanager.SSBSlimeWorldManager
depend: [SlimeWorldManager]
loadbefore: [SuperiorSkyblock2]